/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Hospital;

import Login.Login;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Davor
 */
public class Hospital extends javax.swing.JFrame {

    private JFrame frame;
    public Hospital() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbtnDelete = new javax.swing.JButton();
        jbtnUpdate = new javax.swing.JButton();
        jbtnGPAppointment = new javax.swing.JButton();
        jbtnDoctor = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnPatient = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnPrescription = new javax.swing.JButton();
        jbtnLogin = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtPrescription = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcmbNameOfTablets = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jtxtDose = new javax.swing.JTextField();
        jtxtRefNo = new javax.swing.JTextField();
        jtxtLot = new javax.swing.JTextField();
        jtxtNumberOfTablets = new javax.swing.JTextField();
        jtxtExpDate = new javax.swing.JTextField();
        jtxtPossibleSideEffects = new javax.swing.JTextField();
        jtxtDailyDose = new javax.swing.JTextField();
        jtxtStorageAdvice = new javax.swing.JTextField();
        jtxtFurtherInformation = new javax.swing.JTextField();
        jtxtHowtoUseMedication = new javax.swing.JTextField();
        jtxtDrivingAndUsingMachines = new javax.swing.JTextField();
        jtxtPatientID = new javax.swing.JTextField();
        jtxtPatientAddress = new javax.swing.JTextField();
        jtxtNHSNo = new javax.swing.JTextField();
        jtxtPatientName = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jtxtDateOfBirth = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jtxtIssuedDate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1400, 800));
        setPreferredSize(new java.awt.Dimension(1400, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Hospital Management System");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 1340, 150));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 140, -1));

        jbtnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnUpdate.setText("Update");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 140, -1));

        jbtnGPAppointment.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnGPAppointment.setText("GP Appointment");
        jbtnGPAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGPAppointmentActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnGPAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 190, -1));

        jbtnDoctor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnDoctor.setText("Doctor");
        jbtnDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDoctorActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 140, -1));

        jbtnReset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 130, -1));

        jbtnPatient.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnPatient.setText("Patient");
        jbtnPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPatientActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 100, -1));

        jbtnExit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 20, 80, -1));

        jbtnPrescription.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnPrescription.setText("Prescription");
        jbtnPrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrescriptionActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnPrescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, 140, -1));

        jbtnLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnLogin.setText("Login");
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 20, 140, -1));

        jbtnPrint.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 20, 80, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 720, 1340, 70));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtPrescription.setColumns(20);
        jtxtPrescription.setRows(5);
        jScrollPane2.setViewportView(jtxtPrescription);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 450));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 170, 400, 470));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Patient Prescription");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 930, 80));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Reference No.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jcmbNameOfTablets.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jcmbNameOfTablets.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Make a Selection", "Ibuprofen", "Co-codamol", "Paracetamol", "Amlodipine" }));
        jcmbNameOfTablets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbNameOfTabletsActionPerformed(evt);
            }
        });
        getContentPane().add(jcmbNameOfTablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 200, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Name of Tablets:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Number of Tablets");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Dose (mg):");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("LOT:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Exp. Date:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Daily Dose:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Possible Side Effects:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 670, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Storage Advice:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Further Information:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("How to use Medication:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Driving and Using Machines:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Patient ID:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("NHS Number:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 520, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("Patient Name:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 570, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("Patient Address:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 670, -1, -1));

        jtxtDose.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jtxtDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 200, -1));

        jtxtRefNo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jtxtRefNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 200, -1));

        jtxtLot.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jtxtLot, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 200, -1));

        jtxtNumberOfTablets.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jtxtNumberOfTablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 200, -1));

        jtxtExpDate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jtxtExpDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 570, 200, -1));

        jtxtPossibleSideEffects.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jtxtPossibleSideEffects, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 670, 200, -1));

        jtxtDailyDose.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jtxtDailyDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 620, 200, -1));

        jtxtStorageAdvice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jtxtStorageAdvice, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 320, 200, -1));

        jtxtFurtherInformation.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jtxtFurtherInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 270, 200, -1));

        jtxtHowtoUseMedication.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jtxtHowtoUseMedication, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 420, 200, -1));

        jtxtDrivingAndUsingMachines.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jtxtDrivingAndUsingMachines, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 370, 200, -1));

        jtxtPatientID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jtxtPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 470, 200, -1));

        jtxtPatientAddress.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jtxtPatientAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 670, 200, -1));

        jtxtNHSNo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtxtNHSNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNHSNoActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtNHSNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 520, 200, -1));

        jtxtPatientName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtxtPatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPatientNameActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 570, 200, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("Date of Birth:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 620, -1, -1));

        jtxtDateOfBirth.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtxtDateOfBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDateOfBirthActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtDateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 620, 200, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setText("Issued Date:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        jtxtIssuedDate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jtxtIssuedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 200, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name of Tablets", "Reference No", "Dose (mg)", "Number of Tablets", "LOT", "Issued Date", "Exp Date", "Daily Dose", "Possible Side Effects", "Further Information", "Storage Advice", "Administration", "Driving and Using Medication", "How to Use Medication", "Patient ID", "Doctor NHS No", "Date of Birth", "Patient Address"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 800, 1340, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        // TODO add your handling code here:
        frame = new JFrame();
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit", "Hospital Management Systems", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        // TODO add your handling code here:
        try
        {
            jtxtPrescription.print();
        }
        catch(PrinterException ex)
        {
            Logger.getLogger(Hospital.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jcmbNameOfTabletsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbNameOfTabletsActionPerformed
        // TODO add your handling code here:
        if(jcmbNameOfTablets.getSelectedItem().equals("Ibuprofen"))
        {
            jtxtRefNo.setText("Ibu8568959");
            jtxtDose.setText("2");
            jtxtNumberOfTablets.setText("32");
            jtxtLot.setText("561005875");
            jtxtIssuedDate.setText("06/05/2018");
            jtxtExpDate.setText("04/05/2019");
            jtxtDailyDose.setText("4");
            
            jtxtPossibleSideEffects.setText("Bleeding");
            jtxtFurtherInformation.setText("Place Dispensary");
            jtxtStorageAdvice.setText("Less than 20%");
            jtxtDrivingAndUsingMachines.setText("No");
            jtxtHowtoUseMedication.setText("Use water, No alcohol");
            jtxtPatientID.setText("P9589454");
            jtxtNHSNo.setText("646564");
        }
        
        else if (jcmbNameOfTablets.getSelectedItem().equals("Co-codamol"))
        {
            jtxtRefNo.setText("COCO6758940");
            jtxtDose.setText("500");
            jtxtNumberOfTablets.setText("30");
            jtxtLot.setText("B770034");
            jtxtIssuedDate.setText("06/05/2018");
            jtxtExpDate.setText("04/12/2019");
            jtxtDailyDose.setText("2");
            
            jtxtPossibleSideEffects.setText("Dizziness");
            jtxtFurtherInformation.setText("Place Dispensary");
            jtxtStorageAdvice.setText("Less than 20%");
            jtxtDrivingAndUsingMachines.setText("No");
            jtxtHowtoUseMedication.setText("Use water, No alcohol");
            jtxtPatientID.setText("P9589454");
            jtxtNHSNo.setText("646564");
        }
        
        else if (jcmbNameOfTablets.getSelectedItem().equals("Paracetamol"))
        {
            jtxtRefNo.setText("01729214");
            jtxtDose.setText("500");
            jtxtNumberOfTablets.setText("16");
            jtxtLot.setText("0204324");
            jtxtIssuedDate.setText("07/05/2018");
            jtxtExpDate.setText("04/05/2023");
            jtxtDailyDose.setText("2");
            
            jtxtPossibleSideEffects.setText("Feeling Sick");
            jtxtFurtherInformation.setText("Place Dispensary");
            jtxtStorageAdvice.setText("Less than 25%");
            jtxtDrivingAndUsingMachines.setText("No");
            jtxtHowtoUseMedication.setText("Use water, No alcohol");
            jtxtPatientID.setText("P5562454");
            jtxtNHSNo.setText("875564");
        }
        
        else if (jcmbNameOfTablets.getSelectedItem().equals("Amlodipine"))
        {
            jtxtRefNo.setText("Am05875");
            jtxtDose.setText("5");
            jtxtNumberOfTablets.setText("28");
            jtxtLot.setText("8745475");
            jtxtIssuedDate.setText("06/05/2018");
            jtxtExpDate.setText("04/05/2020");
            jtxtDailyDose.setText("1");
            
            jtxtPossibleSideEffects.setText("Liver Disease");
            jtxtFurtherInformation.setText("Ability to drive may be affected");
            jtxtStorageAdvice.setText("No Special Storage");
            jtxtDrivingAndUsingMachines.setText("No");
            jtxtHowtoUseMedication.setText("Use water, No alcohol");
            jtxtPatientID.setText("P9129454");
            jtxtNHSNo.setText("6346564");
        }
        
        else if (jcmbNameOfTablets.getSelectedItem().equals("Make a Selection"))
        {
            jtxtRefNo.setText("");
            jtxtDose.setText("");
            jtxtNumberOfTablets.setText("");
            jtxtLot.setText("");
            jtxtIssuedDate.setText("");
            jtxtExpDate.setText("");
            jtxtDailyDose.setText("");
            
            jtxtPossibleSideEffects.setText("");
            jtxtFurtherInformation.setText("");
            jtxtStorageAdvice.setText("");
            jtxtDrivingAndUsingMachines.setText("");
            jtxtHowtoUseMedication.setText("");
            jtxtPatientID.setText("");
            jtxtNHSNo.setText("");
        }
    }//GEN-LAST:event_jcmbNameOfTabletsActionPerformed

    private void jtxtNHSNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNHSNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNHSNoActionPerformed

    private void jtxtPatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPatientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPatientNameActionPerformed

    private void jtxtDateOfBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDateOfBirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDateOfBirthActionPerformed

    private void jbtnPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrescriptionActionPerformed
        // TODO add your handling code here:
        String Qty1 = (jtxtRefNo.getText());
        String Qty2 = (jtxtDose.getText());
        String Qty3 = (jtxtNumberOfTablets.getText());
        String Qty4 = (jtxtLot.getText());
        String Qty5 = (jtxtDailyDose.getText());
        String Qty6 = (jtxtPossibleSideEffects.getText());
        String Qty7 = (jtxtFurtherInformation.getText());
        String Qty8 = (jtxtHowtoUseMedication.getText());
        String Qty9 = (jtxtPatientID.getText());
        String Qty10 = (jtxtPatientName.getText());
        String Qty11 = (jtxtDateOfBirth.getText());
        String Qty12 = (jtxtPatientAddress.getText());
        String Qty13 = "";
        
        if(jcmbNameOfTablets.getSelectedItem().equals("Ibuprofen"))
        {
            Qty13 = "Ibuprofen";
        }
        else if(jcmbNameOfTablets.getSelectedItem().equals("Co-codamol"))
        {
            Qty13 = "Co-codamol";
        }
        else if(jcmbNameOfTablets.getSelectedItem().equals("Paracetamol"))
        {
            Qty13 = "Paracetamol";
        }
        else if(jcmbNameOfTablets.getSelectedItem().equals("Amlodipine"))
        {
            Qty13 = "Amlodipine";
        }
        
        jtxtPrescription.setText("");
        jtxtPrescription.append("\t\n\tHospital Management System\n" + "\nPatient Name:\t\t" + Qty10 + "\nDate of Birth:\t\t" + Qty11 + "\nPatient Address:\t\t"
        + "\nPrescription:\t\t" + Qty13 + "\n\nReference No.:" + Qty1 + "\nDose (mg):" + Qty2 + "\nNumber of Tablets:" + Qty3 + "\nLOT:" + Qty4 + "\nDaily Dose:" + Qty5 + "\nPossible Side Effects"
        + Qty6 + "\nFurther Information:" + Qty7 + "\nHow to Use Medication" + Qty8 + "\nPatient ID:" + Qty9 + "\n\n\tPatient Instruction we have introduced a \n\tfree text confirmation\n\t" + 
                "TEXT REMINDERS FOR APPOINTMENT");
    }//GEN-LAST:event_jbtnPrescriptionActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        // TODO add your handling code here:
            jtxtRefNo.setText("");
            jtxtDose.setText("");
            jtxtNumberOfTablets.setText("");
            jtxtLot.setText("");
            jtxtIssuedDate.setText("");
            jtxtExpDate.setText("");
            jtxtDailyDose.setText("");
            
            jtxtPossibleSideEffects.setText("");
            jtxtFurtherInformation.setText("");
            jtxtStorageAdvice.setText("");
            jtxtDrivingAndUsingMachines.setText("");
            jtxtHowtoUseMedication.setText("");
            jtxtPatientID.setText("");
            jtxtPatientName.setText("");
            jtxtDateOfBirth.setText("");
            jtxtPatientAddress.setText("");
            jtxtNHSNo.setText("");
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed
        // TODO add your handling code here:
        Login iLogin = new Login();
        iLogin.setVisible(true);
    }//GEN-LAST:event_jbtnLoginActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{jcmbNameOfTablets.getSelectedItem().toString(),
        jtxtRefNo.getText(), jtxtDose.getText(), jtxtNumberOfTablets.getText(), jtxtLot.getText(), 
        jtxtIssuedDate.getText(), jtxtExpDate.getText(), jtxtDailyDose.getText(), jtxtPossibleSideEffects.getText(),
        jtxtFurtherInformation.getText(), jtxtStorageAdvice.getText(), jtxtDrivingAndUsingMachines.getText(),
        jtxtHowtoUseMedication.getText(), jtxtPatientID.getText(), jtxtNHSNo.getText(), jtxtPatientName.getText(),
        jtxtDateOfBirth.getText(), jtxtPatientAddress.getText()});
        
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if (jTable1.getSelectedRow() == -1)
        {
            if (jTable1.getRowCount() == 0)
            {
                JOptionPane.showMessageDialog(null, "No data to delete", "Hospital Management System", JOptionPane.OK_OPTION);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Select a row to delete", "Hospital Management System", JOptionPane.OK_OPTION);
            }
        }
        else
        {
            model.removeRow(jTable1.getSelectedRow());
        }
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jbtnDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDoctorActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jbtnDoctorActionPerformed

    private void jbtnGPAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGPAppointmentActionPerformed
        // TODO add your handling code here:
        Login iLogin = new Login();
        iLogin.setVisible(true);
    }//GEN-LAST:event_jbtnGPAppointmentActionPerformed

    private void jbtnPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPatientActionPerformed
        // TODO add your handling code here:
        Login iLogin = new Login();
        iLogin.setVisible(true);
    }//GEN-LAST:event_jbtnPatientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hospital().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnDoctor;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnGPAppointment;
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JButton jbtnPatient;
    private javax.swing.JButton jbtnPrescription;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JComboBox<String> jcmbNameOfTablets;
    private javax.swing.JTextField jtxtDailyDose;
    private javax.swing.JTextField jtxtDateOfBirth;
    private javax.swing.JTextField jtxtDose;
    private javax.swing.JTextField jtxtDrivingAndUsingMachines;
    private javax.swing.JTextField jtxtExpDate;
    private javax.swing.JTextField jtxtFurtherInformation;
    private javax.swing.JTextField jtxtHowtoUseMedication;
    private javax.swing.JTextField jtxtIssuedDate;
    private javax.swing.JTextField jtxtLot;
    private javax.swing.JTextField jtxtNHSNo;
    private javax.swing.JTextField jtxtNumberOfTablets;
    private javax.swing.JTextField jtxtPatientAddress;
    private javax.swing.JTextField jtxtPatientID;
    private javax.swing.JTextField jtxtPatientName;
    private javax.swing.JTextField jtxtPossibleSideEffects;
    private javax.swing.JTextArea jtxtPrescription;
    private javax.swing.JTextField jtxtRefNo;
    private javax.swing.JTextField jtxtStorageAdvice;
    // End of variables declaration//GEN-END:variables
}
